/**
 * One rule, aimed at one bug that has bitten twice: a patch script that aborts
 * halfway leaves code referring to a variable it never added. That parses
 * cleanly and throws the instant it runs, and neither node --check nor tsc
 * --checkJs reports it — TypeScript treats the assignment as an implicit
 * global, so it passes silently.
 */
export default [
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
      window: 'readonly',
      document: 'readonly',
      console: 'readonly',
      fetch: 'readonly',
      localStorage: 'readonly',
      sessionStorage: 'readonly',
      navigator: 'readonly',
      location: 'readonly',
      history: 'readonly',
      setTimeout: 'readonly',
      clearTimeout: 'readonly',
      setInterval: 'readonly',
      clearInterval: 'readonly',
      requestAnimationFrame: 'readonly',
      cancelAnimationFrame: 'readonly',
      URL: 'readonly',
      URLSearchParams: 'readonly',
      AbortSignal: 'readonly',
      AbortController: 'readonly',
      Image: 'readonly',
      Blob: 'readonly',
      File: 'readonly',
      FileReader: 'readonly',
      FormData: 'readonly',
      Headers: 'readonly',
      Request: 'readonly',
      Response: 'readonly',
      CustomEvent: 'readonly',
      Event: 'readonly',
      EventTarget: 'readonly',
      MutationObserver: 'readonly',
      ResizeObserver: 'readonly',
      IntersectionObserver: 'readonly',
      matchMedia: 'readonly',
      getComputedStyle: 'readonly',
      alert: 'readonly',
      confirm: 'readonly',
      prompt: 'readonly',
      crypto: 'readonly',
      performance: 'readonly',
      structuredClone: 'readonly',
      queueMicrotask: 'readonly',
      HTMLElement: 'readonly',
      Node: 'readonly',
      SVGElement: 'readonly',
      DOMParser: 'readonly',
      XMLSerializer: 'readonly',
      requestIdleCallback: 'readonly',
      screen: 'readonly',
      frames: 'readonly',
      self: 'readonly',
      top: 'readonly',
      parent: 'readonly',
      devicePixelRatio: 'readonly',
      L: 'readonly',
      },
    },
    rules: { 'no-undef': 'error' },
  },
];
