/**
 * Strong's as a browsable list: one row per classic number, in four orders.
 *
 * The pack's rows are read once per language into a slim in-memory index —
 * the number, the word, its gloss and transliteration, and the folded keys the
 * orders sort on — and every order, section and search works from that. The
 * split meanings STEPBible adds (G2424G Jesus, G2424K Joshua) don't get rows of
 * their own; their glosses ride on their number's row so a search for
 * "Joshua" still finds Ἰησοῦς. The Septuagint-only words (G6000 and up) and the
 * Hebrew prefix entries (H9001 and up) aren't classic numbers and are left out.
 */

import { openDB } from '../../adapters/db';
import type { LibraryRow } from '../../adapters/lexicon-lookup.js';
import type { LibrarySourceAdapter } from '../library/source';
import { wordMatcher } from '../searchWords';
import {
  firstForm,
  greekKey,
  hebrewKey,
  glossKey,
  translitKey,
  latinKey,
  isGreekText,
  isHebrewText,
} from './collate';
import { classicId, displayId, languageColor, shelfName } from './entry';

export type StrongsLang = 'greek' | 'hebrew';
export type StrongsSort = 'number' | 'english' | 'original' | 'used';

export const SORTS: StrongsSort[] = ['number', 'english', 'original', 'used'];

interface IndexRow {
  /** The classic id, padded as the pack keys it: G0026. */
  id: string;
  num: number;
  lang: StrongsLang;
  lemma: string;
  gloss: string;
  translit: string;
  /** The split meanings' glosses, searched along with the row's own. */
  splitGlosses: string[];
  origKey: string;
  glossKey: string;
  /** The gloss's head word alone — "love" for "love, goodwill" and for "to
   *  love" — for matching an English word from another work. */
  headKey: string;
  translitKey: string;
  count: number;
}

/** The last classic number in each language. */
const LAST: Record<StrongsLang, number> = { greek: 5624, hebrew: 8674 };
const PREFIX: Record<StrongsLang, string> = { greek: 'G', hebrew: 'H' };
const STORE: Record<StrongsLang, string> = { greek: 'greek_strongs_entries', hebrew: 'hebrew_strongs_entries' };

// --- The index ---------------------------------------------------------------

const indexes: Partial<Record<StrongsLang, Promise<IndexRow[]>>> = {};

/** Times each number is used, generated by scripts/build-strongs-counts.mjs. */
let countsLoad: Promise<{ greek: number[]; hebrew: number[] }> | null = null;
function loadCounts() {
  countsLoad ??= import('../../data/strongs-counts.json').then((m) => (m.default ?? m) as { greek: number[]; hebrew: number[] });
  return countsLoad;
}

/**
 * Every classic entry in one language. Kept for the session once it has rows;
 * an empty answer (the pack not installed yet) is asked again next time.
 */
function loadIndex(lang: StrongsLang): Promise<IndexRow[]> {
  const found = (indexes[lang] ??= buildIndex(lang).then((rows) => {
    if (!rows.length) delete indexes[lang];
    return rows;
  }));
  return found.catch((err) => {
    delete indexes[lang];
    console.error("Failed to read Strong's:", err);
    return [];
  });
}

async function buildIndex(lang: StrongsLang): Promise<IndexRow[]> {
  const db = await openDB();
  const storeName = STORE[lang];
  if (!db.objectStoreNames.contains(storeName)) return [];
  const prefix = PREFIX[lang];
  // Classic numbers and their splits only — G0001 through G5624G, say — so the
  // Septuagint-only and prefix entries past the end are never read at all.
  const range = IDBKeyRange.bound(`${prefix}0001`, `${prefix}${LAST[lang]}￿`);
  const records = await new Promise<any[]>((resolve, reject) => {
    const req = db.transaction(storeName, 'readonly').objectStore(storeName).getAll(range);
    req.onsuccess = () => resolve(req.result ?? []);
    req.onerror = () => reject(req.error);
  });
  const counts = (await loadCounts())[lang];

  const rows = new Map<string, IndexRow>();
  const splits = new Map<string, string[]>();
  for (const r of records) {
    const m = /^([GH])(\d{4})([A-Za-z]?)$/.exec(String(r.id ?? ''));
    if (!m) continue;
    const gloss = String(r.shortDefinition ?? '').trim();
    if (m[3]) {
      // A split meaning: its gloss is kept for its number's row.
      const base = `${m[1]}${m[2]}`;
      if (gloss) splits.set(base, [...(splits.get(base) ?? []), gloss]);
      continue;
    }
    const num = Number(m[2]);
    const lemma = String(r.lemma ?? '').trim();
    const translit = String(r.transliteration ?? '').trim();
    rows.set(r.id, {
      id: r.id,
      num,
      lang,
      lemma,
      gloss,
      translit,
      splitGlosses: [],
      origKey: lang === 'greek' ? greekKey(firstForm(lemma)) : hebrewKey(firstForm(lemma)),
      glossKey: glossKey(gloss),
      headKey: glossKey(gloss).split(/[,;:/(]/)[0].trim(),
      translitKey: translitKey(translit),
      count: counts[num] ?? 0,
    });
  }
  for (const [base, glosses] of splits) {
    const row = rows.get(base);
    // A split that only repeats its number's gloss adds nothing to search on.
    if (row) row.splitGlosses = glosses.filter((g) => g !== row.gloss);
  }
  return [...rows.values()];
}

// --- Orders and sections -----------------------------------------------------

const GREEK_LETTERS = 'αβγδεζηθικλμνξοπρστυφχψω'.split('');
const HEBREW_LETTERS = 'אבגדהוזחטיכלמנסעפצקרשת'.split('');
const LATIN_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
const OTHER = '#';

/** Number order comes in bands of 500: G1–G499, G500–G999 and so on. */
const BAND = 500;
/** Most used comes in bands too, busiest first. */
const USE_BANDS = [1000, 500, 100, 50, 10, 2, 1, 0];

function compare(sort: StrongsSort) {
  switch (sort) {
    case 'number':
      return (a: IndexRow, b: IndexRow) => a.num - b.num;
    case 'english':
      return (a: IndexRow, b: IndexRow) =>
        a.glossKey < b.glossKey ? -1 : a.glossKey > b.glossKey ? 1 : a.num - b.num;
    case 'original':
      return (a: IndexRow, b: IndexRow) =>
        a.origKey < b.origKey ? -1 : a.origKey > b.origKey ? 1 : a.num - b.num;
    case 'used':
      return (a: IndexRow, b: IndexRow) => b.count - a.count || a.num - b.num;
  }
}

/** Which section a row files under. Keys are never plain integers, so an
 *  object keyed by them keeps the order they were added in. */
function sectionOf(row: IndexRow, sort: StrongsSort): string {
  switch (sort) {
    case 'number':
      return `n${Math.floor(row.num / BAND) * BAND || 1}`;
    case 'english': {
      const c = row.glossKey.charAt(0).toUpperCase();
      return LATIN_LETTERS.includes(c) ? c : OTHER;
    }
    case 'original':
      return row.origKey.charAt(0) || OTHER;
    case 'used':
      return `u${USE_BANDS.find((b) => row.count >= b) ?? 0}`;
  }
}

function sectionsFor(lang: StrongsLang, sort: StrongsSort): string[] {
  switch (sort) {
    case 'number': {
      const out: string[] = [];
      for (let from = 0; from <= LAST[lang]; from += BAND) out.push(`n${from || 1}`);
      return out;
    }
    case 'english':
      return [...LATIN_LETTERS, OTHER];
    case 'original':
      return lang === 'greek' ? GREEK_LETTERS : HEBREW_LETTERS;
    case 'used':
      return USE_BANDS.map((b) => `u${b}`);
  }
}

function railLabel(key: string): string {
  if (key.startsWith('n')) {
    const from = Number(key.slice(1));
    return from < 1000 ? String(from) : `${from / 1000}k`;
  }
  if (key.startsWith('u')) {
    const b = Number(key.slice(1));
    return b >= 1000 ? '1k+' : String(b);
  }
  return key;
}

function sectionLabelFor(lang: StrongsLang) {
  return (key: string): string => {
    if (key.startsWith('n')) {
      const from = Number(key.slice(1));
      const to = Math.min(LAST[lang], (from === 1 ? 0 : from) + BAND - 1);
      return `${PREFIX[lang]}${from}–${PREFIX[lang]}${to}`;
    }
    if (key.startsWith('u')) {
      const b = Number(key.slice(1));
      const i = USE_BANDS.indexOf(b);
      const above = i > 0 ? USE_BANDS[i - 1] - 1 : null;
      if (b === 0) return 'Not found in the text counted';
      if (b === 1) return 'Used once';
      return above == null ? `Used ${b.toLocaleString()}+ times` : `Used ${b}–${above.toLocaleString()} times`;
    }
    return key;
  };
}

/** The sort key a typed prefix is matched against, per order. */
function sortKeyOf(row: IndexRow, sort: StrongsSort): string {
  switch (sort) {
    case 'number':
      return String(row.num);
    case 'english':
      return row.glossKey;
    case 'original':
      return row.origKey;
    case 'used':
      return String(row.count);
  }
}

function toRow(r: IndexRow, sort: StrongsSort): LibraryRow {
  return {
    id: r.id,
    name: r.lemma,
    sortKey: sortKeyOf(r, sort),
    isPlace: false,
    detail: r.gloss,
    tag: displayId(r.id),
    tagColor: languageColor(r.lang),
    nameLang: r.lang,
    meta: r.count ? `${r.count.toLocaleString()}×` : '',
    markName: shelfName(r.id, r.lemma, r.gloss),
  };
}

/** One language's rows in one order, split into sections. Kept per order. */
const sectioned = new Map<string, Map<string, LibraryRow[]>>();

async function sectionsOf(lang: StrongsLang, sort: StrongsSort): Promise<Map<string, LibraryRow[]>> {
  const key = `${lang}|${sort}`;
  const held = sectioned.get(key);
  if (held) return held;
  const index = await loadIndex(lang);
  const out = new Map<string, LibraryRow[]>();
  if (!index.length) return out;
  for (const r of [...index].sort(compare(sort))) {
    const s = sectionOf(r, sort);
    let list = out.get(s);
    if (!list) out.set(s, (list = []));
    list.push(toRow(r, sort));
  }
  sectioned.set(key, out);
  return out;
}

// --- Search ------------------------------------------------------------------

const SEARCH_LIMIT = 100;

/**
 * Search both languages at once: a number ("26", "G26", "H430"), Greek or
 * Hebrew letters with or without their accents and points, a transliteration
 * ("agape", "elohim"), or an English meaning, matched by whole words and their
 * forms the way the app's search bar matches ("love" finds "to love", not
 * "beloved").
 */
async function searchStrongs(query: string, sort: StrongsSort): Promise<LibraryRow[]> {
  const q = query.trim();
  if (!q) return [];
  const [greek, hebrew] = await Promise.all([loadIndex('greek'), loadIndex('hebrew')]);

  const num = /^([GH])?\s*0*(\d{1,4})[A-Za-z]?$/i.exec(q);
  if (num) {
    const n = Number(num[2]);
    const want = num[1]?.toUpperCase();
    const pools = want === 'G' ? [greek] : want === 'H' ? [hebrew] : [greek, hebrew];
    return pools.flatMap((pool) => pool.filter((r) => r.num === n)).map((r) => toRow(r, sort));
  }

  const ranked: { row: IndexRow; rank: number }[] = [];
  if (isGreekText(q) || isHebrewText(q)) {
    const greekQ = isGreekText(q);
    const key = greekQ ? greekKey(q) : hebrewKey(q);
    if (!key) return [];
    for (const r of greekQ ? greek : hebrew) {
      if (r.origKey === key) ranked.push({ row: r, rank: 0 });
      else if (r.origKey.startsWith(key)) ranked.push({ row: r, rank: 1 });
      else if (key.length >= 2 && r.origKey.includes(key)) ranked.push({ row: r, rank: 2 });
    }
  } else {
    const matcher = wordMatcher(q, 'all');
    const plain = latinKey(q);
    const asTranslit = translitKey(q);
    for (const r of [...greek, ...hebrew]) {
      let rank = -1;
      if (r.glossKey === plain || (asTranslit && r.translitKey === asTranslit)) rank = 0;
      else if (matcher.test(r.gloss)) rank = 1;
      else if (asTranslit.length >= 2 && r.translitKey.startsWith(asTranslit)) rank = 2;
      else if (r.splitGlosses.some((g) => matcher.test(g))) rank = 3;
      if (rank >= 0) ranked.push({ row: r, rank });
    }
  }
  // Best match first; among equals, the word the Bible uses most.
  ranked.sort((a, b) => a.rank - b.rank || b.row.count - a.row.count || a.row.num - b.row.num);
  return ranked.slice(0, SEARCH_LIMIT).map(({ row }) => toRow(row, sort));
}

/**
 * The classic entries an English word translates, most used first — for
 * lighting the Strong's tab from another work. Matched on the gloss's head
 * word, so "love" finds ἀγάπη (love) and ἀγαπάω (to love) but not every gloss
 * that mentions love somewhere.
 */
export async function strongsForTerm(term: string): Promise<string[]> {
  const key = glossKey(term).split(/[,;:/(]/)[0].trim();
  if (!key) return [];
  const [greek, hebrew] = await Promise.all([loadIndex('greek'), loadIndex('hebrew')]);
  return [...greek, ...hebrew]
    .filter((r) => r.headKey === key)
    .sort((a, b) => b.count - a.count || a.num - b.num)
    .map((r) => r.id);
}

// --- In this chapter ---------------------------------------------------------

/** Every classic number tagged in one chapter of the installed original texts. */
async function numbersInChapter(book: string, chapter: number, lang: StrongsLang): Promise<Set<string>> {
  const db = await openDB();
  if (!db.objectStoreNames.contains('morphology')) return new Set();
  const records = await new Promise<any[]>((resolve) => {
    const store = db.transaction('morphology', 'readonly').objectStore('morphology');
    if (!store.indexNames.contains('book_chapter_verse_word')) return resolve([]);
    const req = store
      .index('book_chapter_verse_word')
      .getAll(IDBKeyRange.bound([book, chapter], [book, chapter, Infinity]));
    req.onsuccess = () => resolve(req.result ?? []);
    req.onerror = () => resolve([]);
  });
  const prefix = PREFIX[lang];
  const out = new Set<string>();
  for (const m of records) {
    const id = String(m.strongsId ?? '');
    if (id.toUpperCase().startsWith(prefix)) out.add(classicId(id));
  }
  return out;
}

// --- The list ----------------------------------------------------------------

const SORT_KEY = 'projectbible_strongs_sort';

/** The order the list was last left in, on this device. */
export function savedSort(): StrongsSort {
  try {
    const s = localStorage.getItem(SORT_KEY) as StrongsSort | null;
    return s && SORTS.includes(s) ? s : 'number';
  } catch {
    return 'number';
  }
}

export function saveSort(sort: StrongsSort): void {
  try {
    localStorage.setItem(SORT_KEY, sort);
  } catch {
    // Private browsing: the order just isn't remembered.
  }
}

/** The order after this one, for the one-button cycle. */
export function nextSort(sort: StrongsSort): StrongsSort {
  return SORTS[(SORTS.indexOf(sort) + 1) % SORTS.length];
}

/** How the sort button names an order. */
export function sortLabel(sort: StrongsSort, lang: StrongsLang): string {
  switch (sort) {
    case 'number':
      return '1–9';
    case 'english':
      return 'A–Z';
    case 'original':
      return lang === 'greek' ? 'α–ω' : 'א–ת';
    case 'used':
      return 'Most used';
  }
}

/** The order in words, for the button's tooltip and the subtitle. */
export function sortName(sort: StrongsSort, lang: StrongsLang): string {
  switch (sort) {
    case 'number':
      return 'By number';
    case 'english':
      return 'By English meaning';
    case 'original':
      return lang === 'greek' ? 'In Greek order' : 'In Hebrew order';
    case 'used':
      return 'Most used first';
  }
}

/** The language an id belongs to. */
export function langOf(id: string): StrongsLang {
  return /^H/i.test(id) ? 'hebrew' : 'greek';
}

export function strongsSource(lang: StrongsLang, sort: StrongsSort): LibrarySourceAdapter {
  const prefixMatch = (sortKey: string) => {
    // Typing to jump: digits find a number, letters an English meaning.
    if (sort === 'number' && /^\d+$/.test(sortKey)) {
      const n = Number(sortKey);
      return `n${Math.floor(n / BAND) * BAND || 1}`;
    }
    if (sort === 'english') {
      const c = sortKey.charAt(0).toUpperCase();
      return LATIN_LETTERS.includes(c) ? c : OTHER;
    }
    if (sort === 'original') {
      const c = sortKey.charAt(0);
      return (lang === 'greek' ? GREEK_LETTERS : HEBREW_LETTERS).includes(c) ? c : '';
    }
    return '';
  };

  return {
    key: 'strongs',
    pack: 'lexical',
    label: 'Strong’s',
    subtitle: lang === 'greek' ? 'Strong’s Greek dictionary' : 'Strong’s Hebrew dictionary',
    searchPlaceholder: 'Number, word or meaning…',
    filters: [{ key: 'all', label: 'All', test: () => true }],
    badges: [],
    letters: sectionsFor(lang, sort),
    railLabel,
    sectionLabel: sectionLabelFor(lang),
    letterOf: prefixMatch,
    missingPacks: {
      title: 'Get Strong’s',
      note: 'Strong’s Hebrew and Greek dictionary: every word of the original Bible, with its meaning, forms and every place it’s used.',
    },

    async getLetterCounts() {
      const sections = await sectionsOf(lang, sort);
      const out: Record<string, number> = {};
      for (const key of sectionsFor(lang, sort)) {
        const n = sections.get(key)?.length ?? 0;
        if (n) out[key] = n;
      }
      return out;
    },

    async getRowsForLetter(letter: string) {
      return (await sectionsOf(lang, sort)).get(letter) ?? [];
    },

    search: (query: string) => searchStrongs(query, sort),

    async getRowsInChapter(book: string, chapter: number) {
      const [numbers, index] = await Promise.all([numbersInChapter(book, chapter, lang), loadIndex(lang)]);
      return index
        .filter((r) => numbers.has(r.id))
        .sort(compare(sort))
        .map((r) => toRow(r, sort));
    },

    async locate(id: string | number) {
      const want = classicId(String(id));
      if (langOf(want) !== lang) return null;
      const row = (await loadIndex(lang)).find((r) => r.id === want);
      return row ? sectionOf(row, sort) : null;
    },
  };
}
